### ISSUE TITLE
Error when trying to roll character attributes

### ISSUE THREAD

**Issue by ObiWanCanOweMe** [Forelius/kernethalascsb#1]
After clicking the d20 icon on the character sheet nothing happens in the interface. However, the following error is displayed on the console:

`VM22073:3 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'execute')
    at eval (eval at processFormulas (ComputablePhrase.js:124:40), <anonymous>:3:53)
    at processFormulas (ComputablePhrase.js:124:132)
    at async processFormulas (ComputablePhrase.js:96:46)
    at async ComputablePhrase.compute (ComputablePhrase.js:150:34)
    at async Label.js:581:13`

Foundry v11.315
### Active Modules
KerNethalasCSB v1.1.8
Chat Commander v2.0.2 [Bugs URL](https://gitlab.com/woodentavern/foundryvtt-chat-command-lib/-/issues)
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)

**Comment by Forelius** [comment]
I tried to reproduce the error and was not able to. I'll need to get more info to try and figure out what is happening.
Does the dialog appear, asking if you want to roll attributes, when you click the button? Did you import the macros, and if so, does the player receiving the error have access to them?

**Comment by ObiWanCanOweMe** [comment]
Turns out I had not imported the macros (thought I did). Chalking this up to the macro directory not being visible by default (which is obviously not an issue with your module). Apologies for bothering you :)

**Comment by Forelius** [comment]
No problem and glad you got it working.
