### ISSUE TITLE
Problem rolling skills with bonus

### ISSUE THREAD

**Issue by mughtdred** [Forelius/kernethalascsb#2]
First of all thank you for the module, which is a marvel, it is being very helpful along with your youtube videos to play Ker Nethalas. I just wanted to tell you about an error that I am having and that in your videos does not happen.

When I make a skill roll and add a bonus, in the result the target value comes out incorrect (for example, Bladed weapon skill: 60 + Bonus 10; the target should be "<=70", but I get 6010). 

I send you an image to see it better.

Do you know why it could be?
Thank you very much
![ker nethalas 02](https://github.com/Forelius/kernethalascsb/assets/174277907/6fa279b2-a38e-4d98-9777-b22c6e12c403)

**Comment by Forelius** [comment]
It looks like a numeric is being treated as a string. Shouldn't be too hard to fix. I'll work on it today.

**Comment by Forelius** [comment]
There is a small change to a macro named KNRollD100. I will publish a new release, but you won't have to do the full upgrade to get this change, you can just delete your macros and re-import those only.

I know this is unorthodox, but you could also just copy paste this code into KNRollD100, replacing what was there.
```
let roll = 0;
if (scope.roll){
    roll = scope.roll;
} else{
    let rawRoll = await new Roll(`1d100`).roll();
    roll = rawRoll.total;
}
const rollTens = Math.floor(roll/10);
const rollOnes = roll%10;
let moddedRoll = roll;
let isDoubles = rollTens==rollOnes;
let moddedNotation = '';

const finalTarget = Number(scope.skillVal) + Number(scope.skBonus);
const plusMinus = scope.skBonus == 0 ? '' : scope.skBonus > 0 ? '+' : '';
const stTarget = `${plusMinus}${scope.skBonus}`;

if (scope.advVal == 'a') {
  moddedRoll = rollTens < rollOnes ? moddedRoll : (rollOnes * 10) + rollTens;
  moddedNotation = `(${moddedRoll} <i>advantage</i>)`
} else if (scope.advVal == 'd') {
  moddedRoll = rollTens > rollOnes ? moddedRoll : (rollOnes*10) + rollTens;
  moddedNotation = `(${moddedRoll} <i>disadvantage</i>)`
}

let successMsg = ' Failed';

if (moddedRoll<=finalTarget) {
  if (isDoubles==true){
    successMsg=' <strong>Critical Success!</strong>';
  } else{
    successMsg=' Success';
  }
} else if (isDoubles==true) {
  successMsg=' <strong>Fumble!<strong>';
}

const results= ` ${moddedNotation} = ${successMsg}<br/>Other Bonus: ${stTarget}</br><i>Target: <= ${finalTarget}</i>`;
return results;
```

**Comment by Forelius** [comment]
Release 1.1.9 addresses this issue.

**Comment by mughtdred** [comment]
Fixed!!!
Thank you very much, it works perfectly. 

If I find any other bug I'll let you know, because the module is awesome. 

I thank you again for the great work you have done and I hope to watch the pt. 3 on youtube if you plan to do it.

**Comment by jessewritescode** [comment]
Thanks @Forelius
